@startuml
participant main_function as "メイン関数"
participant calculate  as "calculate()関数"
participant getinput as "getInput()関数"

main_function -> calculate : 呼び出す
calculate -> getinput : 呼び出す
getinput --> calculate : 入力データを返す
calculate --> main_function : 計算結果を返す 

@enduml