@startuml
participant m as "メイン関数" 
participant c as "calculate()関数"  
participant g as "getInput()関数" 

activate m
m -> c : 呼び出す
activate c
c -> g : 呼び出す
activate g
g --> c : 入力データを返す
deactivate g
c --> m : 計算結果を返す 
deactivate c
@enduml