@startuml
left to right direction
package system{
    usecase "履修科目" as f1
    usecase "UNIVERSAL PASSPORT" as f2
    usecase "学校からのお知らせ"as f3
    usecase "授業からのお知らせ"as f4
}
:学生:-->(f1)
:学生:-->(f2)
:学生:-->(f3)
:学生:-->(f4)
@enduml